version: 2.1

commands:
  build-and-push:
    steps:
      - checkout
      - run:
          name: Set tag
          command: export DOCKER_TAG=$(echo $CIRCLE_JOB | cut -c 4-)
      - run:
          name: Enter directory
          command: cd $DOCKER_TAG
      - run:
          name: Login to docker
          command: echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin
      - run:
          name: Build the image
          command: docker build -t "tidyapp/php:${DOCKER_TAG}" .
      - run:
          name: Deploy the image
          command: docker push "tidyapp/php:${DOCKER_TAG}"
jobs:
  php7-fpm-alpine:
    machine: true
    steps:
      - build-and-push

workflows:
  multi-build:
    jobs:
      - php7-fpm-alpine
