version: 2.1

commands:
  build-and-push:
    steps:
      - checkout
      - run:
          name: Set docker tag
          command: |
            echo 'export DOCKER_TAG=$(echo $CIRCLE_JOB | sed "s/_/./" | cut -c 4-)' >> $BASH_ENV
            source $BASH_ENV
            echo "Docker Tag: $DOCKER_TAG"
      - run:
          name: Login to docker
          command: echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin
      - run:
          name: Build the image
          command: docker build -t "tidyapp/php:$DOCKER_TAG" --build-arg "BASEIMAGE=jitesoft/php:$DOCKER_TAG" .
      - run:
          name: Deploy the image
          command: docker push "tidyapp/php:$DOCKER_TAG"

jobs:
  php7_3-fpm:
    machine: true
    steps:
      - build-and-push
  php7_2-fpm:
    machine: true
    steps:
      - build-and-push

workflows:
  commit:
    jobs:
      - php7_3-fpm
      - php7_2-fpm

  nightly:
    jobs:
      - php7_3-fpm
      - php7_2-fpm
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
