version: 2.1

commands:
  build-and-push:
    steps:
      - checkout
      - run:
          name: Enter directory
          command: cd $CIRCLE_JOB
      - run:
          name: Login to docker
          command: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: Build the image
          command: docker build -t tidyapp/php:$CIRCLE_JOB .
      - run:
          name: Deploy the image
          command: docker push tidyapp/php:$CIRCLE_JOB
jobs:
  7-fpm-alpine:
    machine: true
    steps:
      - build-and-push

workflows:
  multi-build:
    jobs:
      - 7-fpm-alpine
